# Generated by Django 5.2.12 on 2026-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('preparing', 'Готовится к доставке'), ('in_delivery', 'В процессе доставки'), ('ready', 'Готов к получению'), ('completed', 'Получен')], default='preparing', max_length=20),
        ),
    ]
