# Generated by Django 5.2.12 on 2026-04-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_id_alter_book_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Вектор описания'),
        ),
    ]
